### ISSUE TITLE
Use Discord OAuth and create API for the bot to improve identification

### ISSUE THREAD

**Issue by amishshah** [unicsmcr/hs_discord_bot#5]
1. The current identification process is clunky and involves the user finding their own User ID, and then messaging that to the bot in the form `!identify <id>`.

2. It also means that if a user changes any of their HS details (e.g. joins/leaves a team), they would have to re-identify with the bot for these changes to register.

I'm not really sure of the best way to approach the first problem, it might be good to implement OAuth for hs_auth but this would require a significant rewrite of hs_auth.

As for the second issue, we could have `hs_auth` use Discord webhooks, and setup a webhook in a private text channel. If there is a change to the user's team, hs_auth could post to the webhook, and the bot could listen to messages in that channel and use it to update the roles and channels.

**Comment by seanjparker** [comment]
For the first problem, I agree that we should look into adding OAuth on hs_auth at some point, but for now how about we do the following:

- Button on hs_hub to join the discord channel
- On the discord channel they get a message from the bot containing a link like `https://hub.studenthack2020.com/discord/identify/<discord_id>`
- Have a basic route on the hub that sends a POST request to a webhook (either created beforehand or URL encoded in the initial link?) with the message contents as something like `{ discord_id: <discord_id>,  auth_id: <auth_id> }`
- That webhook posts the message to a hidden channel, the bot would parse the message to get the discord user id and hs_auth user id

I'm not completely familiar with the discord API but from my understanding I _think_ that it's possible,  @amishshah let me know if it's not possible the way I described above 😄 

I think we can do that for the second issue, @kzalys what do you think?

**Comment by amishshah** [comment]
Sounds good!

I'm guessing the link would have to be messaged directly to the user so they don't accidentally click on someone else's. There's a slight issue here in where some Discord users can have their DMs disabled for people they aren't friends with, so the bot won't be able to message them and they won't be able to message the bot.

~~We could just tell people to enable their DMs for the Hackathon server, since they wouldn't be able to identify any other way without OAuth.~~

**Edit:** We can use [OAuth with Discord](https://discordapp.com/developers/docs/topics/oauth2) to implement this! Once the user has logged into hs_hub, they should be able to click a verify with Discord button that authenticates them in Discord, then we'd have their authId and discordId.

**Comment by amishshah** [comment]
So to get this working, the following things need to be done:

- Setting up a route on the hub to handle the OAuth response from Discord
- Creating an API for the bot so that this data can be sent to it. Using the webhooks probably isn't the best idea since it will be ratelimited if a lot of users try to verify at once.

**Comment by amishshah** [comment]
Completed in https://github.com/unicsmcr/hs_discord_bot_api
